const recipesDetails = [
  {
    id: 642169,
    title: 'Edamane Hummus',
    image: 'https://spoonacular.com/recipeImages/642169-556x370.jpg',
    summary: "Need a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan hor d'oeuvre</b>? Edamame Hummus could be an awesome recipe to try. This recipe serves 6. For <b>67 cents per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. One serving contains <b>177 calories</b>, <b>6g of protein</b>, and <b>14g of fat</b>. It is brought to you by Foodista. 4 people were glad they tried this recipe. This recipe is typical of middl eastern cuisine. If you have ground coriander, garlic, flat-leaf parsley, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes about <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 56%</b>. <a href=\"https://spoonacular.com/recipes/edamame-hummus-330423\">Edamame Hummus</a>, <a href=\"https://spoonacular.com/recipes/edamame-hummus-527611\">Edamame Hummus</a>, and <a href=\"https://spoonacular.com/recipes/edamame-hummus-567530\">Edamame Hummus</a> are very similar to this recipe.",
    instructions: '<ol><li>Boil the edamame in salted water for 4 to 5 minutes.  Drain.</li><li>In a food processor, puree the Edamame, tahini, water, lemon zest and juice, garlic, salt, cumin, coriander, and chili flakes (optional) until smooth.</li><li>With the motor running, slowly drizzle in 2 tablespoons of olive oil and mix until absorbed.</li><li>Transfer to a small bowl, stir in the parsley and drizzle with remaining oil. Serve, or refrigerate, covered, up to 3 days.</li></ol>',
  },
  {
    id: 642169,
    title: 'Edamane Hummus',
    image: 'https://spoonacular.com/recipeImages/642169-556x370.jpg',
    summary: "Need a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan hor d'oeuvre</b>? Edamame Hummus could be an awesome recipe to try. This recipe serves 6. For <b>67 cents per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. One serving contains <b>177 calories</b>, <b>6g of protein</b>, and <b>14g of fat</b>. It is brought to you by Foodista. 4 people were glad they tried this recipe. This recipe is typical of middl eastern cuisine. If you have ground coriander, garlic, flat-leaf parsley, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes about <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 56%</b>. <a href=\"https://spoonacular.com/recipes/edamame-hummus-330423\">Edamame Hummus</a>, <a href=\"https://spoonacular.com/recipes/edamame-hummus-527611\">Edamame Hummus</a>, and <a href=\"https://spoonacular.com/recipes/edamame-hummus-567530\">Edamame Hummus</a> are very similar to this recipe.",
    instructions: '<ol><li>Boil the edamame in salted water for 4 to 5 minutes.  Drain.</li><li>In a food processor, puree the Edamame, tahini, water, lemon zest and juice, garlic, salt, cumin, coriander, and chili flakes (optional) until smooth.</li><li>With the motor running, slowly drizzle in 2 tablespoons of olive oil and mix until absorbed.</li><li>Transfer to a small bowl, stir in the parsley and drizzle with remaining oil. Serve, or refrigerate, covered, up to 3 days.</li></ol>',
  }, {
    id: 642169,
    title: 'Edamane Hummus',
    image: 'https://spoonacular.com/recipeImages/642169-556x370.jpg',
    summary: "Need a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan hor d'oeuvre</b>? Edamame Hummus could be an awesome recipe to try. This recipe serves 6. For <b>67 cents per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. One serving contains <b>177 calories</b>, <b>6g of protein</b>, and <b>14g of fat</b>. It is brought to you by Foodista. 4 people were glad they tried this recipe. This recipe is typical of middl eastern cuisine. If you have ground coriander, garlic, flat-leaf parsley, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes about <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 56%</b>. <a href=\"https://spoonacular.com/recipes/edamame-hummus-330423\">Edamame Hummus</a>, <a href=\"https://spoonacular.com/recipes/edamame-hummus-527611\">Edamame Hummus</a>, and <a href=\"https://spoonacular.com/recipes/edamame-hummus-567530\">Edamame Hummus</a> are very similar to this recipe.",
    instructions: '<ol><li>Boil the edamame in salted water for 4 to 5 minutes.  Drain.</li><li>In a food processor, puree the Edamame, tahini, water, lemon zest and juice, garlic, salt, cumin, coriander, and chili flakes (optional) until smooth.</li><li>With the motor running, slowly drizzle in 2 tablespoons of olive oil and mix until absorbed.</li><li>Transfer to a small bowl, stir in the parsley and drizzle with remaining oil. Serve, or refrigerate, covered, up to 3 days.</li></ol>',
  }, {
    id: 642169,
    title: 'Edamane Hummus',
    image: 'https://spoonacular.com/recipeImages/642169-556x370.jpg',
    summary: "Need a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan hor d'oeuvre</b>? Edamame Hummus could be an awesome recipe to try. This recipe serves 6. For <b>67 cents per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. One serving contains <b>177 calories</b>, <b>6g of protein</b>, and <b>14g of fat</b>. It is brought to you by Foodista. 4 people were glad they tried this recipe. This recipe is typical of middl eastern cuisine. If you have ground coriander, garlic, flat-leaf parsley, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes about <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 56%</b>. <a href=\"https://spoonacular.com/recipes/edamame-hummus-330423\">Edamame Hummus</a>, <a href=\"https://spoonacular.com/recipes/edamame-hummus-527611\">Edamame Hummus</a>, and <a href=\"https://spoonacular.com/recipes/edamame-hummus-567530\">Edamame Hummus</a> are very similar to this recipe.",
    instructions: '<ol><li>Boil the edamame in salted water for 4 to 5 minutes.  Drain.</li><li>In a food processor, puree the Edamame, tahini, water, lemon zest and juice, garlic, salt, cumin, coriander, and chili flakes (optional) until smooth.</li><li>With the motor running, slowly drizzle in 2 tablespoons of olive oil and mix until absorbed.</li><li>Transfer to a small bowl, stir in the parsley and drizzle with remaining oil. Serve, or refrigerate, covered, up to 3 days.</li></ol>',
  },
];

export default recipesDetails;
